### ISSUE TITLE
Forgotten vue-easy-lightbox.es5.common.min.js in v0.4.1

### ISSUE THREAD

**Issue by sv63rus** [XiongAmao/vue-easy-lightbox#16]
Hi! 
in package.json "main": "dist/vue-easy-lightbox.es5.common.min.js",
but actually this file not exist at tag v.0.4.1. 
This is the reason of error while reload page

Error during render : /xxxxxxx/application
{ Error: Cannot find module 'vue-easy-lightbox'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at r (/home/xxxx/xxxx/xxxxxxx/node_modules/vue-server-renderer/build.dev.js:9303:16)
    at Object.vue-easy-lightbox (webpack:/external "vue-easy-lightbox":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)

We use vuestorefront https://www.vuestorefront.io/

Please fix it or add new tag 0.5.0 because only 0.4.1 present

Best regards

P.S. It was happend because I manually check tag at github repository and add in my package.json 
as "vue-easy-lightbox": "^0.4.1"

When add your module by 'npm  install ... ' or 'yarn add ...' all works fine.

**Comment by XiongAmao** [comment]
I'm so sorry.  The problem has fixed in v0.5.0.

I am not very familiar with the github release and Tags. So.. I forgot it ... 😅
Tag v0.5.0 has been added now.

`npm install` update doesn't work when using '^' and the major version is less than 1 `"^major.minor.patch"`
If you have added `"vue-easy-lightbox:": "^0.4.1" ` to package.json. When you run `npm install`, it will only install "^0.4.x". So you should manully  change it to "^0.5.x" or ">=0.4.1 <1" before v1.0 released.

[version control explain](https://stackoverflow.com/questions/39533030/how-do-i-install-the-latest-minor-version-of-a-package-on-npm)

And [semver.npmjs.com](https://semver.npmjs.com/) can help us to calc it.
