### ISSUE TITLE
Problem requested 2 times

### ISSUE THREAD

**Issue by k3341095** [XiongAmao/vue-easy-lightbox#49]
Why do you ask twice when switching images?

Even if I look at the demo site, I ask for it twice.

A 1MB file consumes 2MB of traffic.

If you pass the image, the request enters twice, doubling the traffic
Is it intended?
Is it a bug?

Couldn't it be modified to request only once?

**Comment by XiongAmao** [comment]
Yes, it's intentional.

I use a hidden `<img>` to check if the resource can be loaded successfully.If it succeeds,  the image will be displayed, otherwise the error placeholder will be displayed.

In general, the second time the `<img>` is loaded, it will not cost your network bandwidth, but will be loaded from the local cache. Because popular web server(like nginx) or cdn services will provide http response cache headers(depends on your settings), which the browser will use to decide whether to cache the http `get` request or not. See this [article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching).

If you have chrome devtool turned on, make sure you don't have 'Disable Cache' checked.
![image.png](https://i.loli.net/2020/09/02/5TwmRaxoMhvjEW7.png)
